apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiransaket-express-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiransaket-express-frontend
  template:
    metadata:
      labels:
        app: kiransaket-express-frontend
    spec:
      containers:
        - name: kiransaket-express-frontend
          image: docker.io/kiransaket/express-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
           - name: BACKEND_URL
             value: http://kiransaket-backend.default.svc.cluster.local:5000
             
---
apiVersion: v1
kind: Service
metadata:
  name: kiransaket-express-frontend
spec:
  selector:
    app: kiransaket-express-frontend
  ports:
    -  port: 80
       targetPort: 3000
  
