# # apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongo
#   template:
#     metadata:
#       labels:
#         app: mongo
#     spec:
#       containers:
#         - name: mongo
#           image: mongo
#           ports:
#             - containerPort: 27017
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
# spec:
#   selector:
#     app: mongo
#   ports:
#     - port: 27017
#       targetPort: 27017
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: docker.io/mongo-express
          env:
            - name: mongo-express
              value: mongo.default.svc.cluster.local:80
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - port: 80
      targetPort: 8081
